name: Deploy Galbi Creator

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Move build output to public directory
      run: |
        mkdir -p public
        mv dist/* public/

    - name: Create GitHub Pages specific files
      run: |
        # Ensure GitHub Pages serves the right directory
        touch public/.nojekyll
        
        # Create a custom 404 page
        cat > public/404.html << 'EOL'
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Page Not Found | Galbi Creator</title>
          <script>window.location.href = '/Galbi_Creator/';</script>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              height: 100vh;
              margin: 0;
              padding: 20px;
              text-align: center;
              background: linear-gradient(135deg, #6e4aff, #47a0ff);
              color: white;
            }
            h1 { font-size: 3rem; margin-bottom: 1rem; }
            p { font-size: 1.2rem; margin-bottom: 2rem; }
            a {
              text-decoration: none;
              color: white;
              background: rgba(255,255,255,0.2);
              padding: 10px 20px;
              border-radius: 5px;
              transition: background 0.3s;
            }
            a:hover { background: rgba(255,255,255,0.3); }
          </style>
        </head>
        <body>
          <h1>Page Not Found</h1>
          <p>The page you were looking for doesn't exist.</p>
          <a href="/Galbi_Creator/">Go to Homepage</a>
        </body>
        </html>
        EOL
      
    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.secret }}  # Use your GitHub token
        publish_dir: ./public   # Set correct directory for GitHub Pages
        keep_files: false  # Optional: Clear previous files before deploying
